# -*- coding: utf-8 -*-


"""
@version: 1.0
@author: clark
@file: const.py
@time: 2017/7/10 01:04
@change_time:
1.2017/7/10 01:04
"""

MIN_SCORE = -float("inf")

Epsion = 1e-15

TYPE_CATEGORY = 1
TYPE_NUMERICAL = 2

CATEGORY_PERCENTAGE = 0.98      # 取98%的比例

FEATURE_NAME_DEFAULT = "auto"

DEFAULT_NUM_LEAVES = 50
DEFAULT_MAX_DEPTH = 10
DEFAULT_LEARNING_RATE = 0.1
DEFAULT_NUM_ESTIMATORS = 10
DEFAULT_MAX_BIN = 50
DEFAULT_MIN_SPLIT_GAIN = 1e-3
DEFAULT_REG_ALPHA = 0
DEFAULT_REG_LAMBDA = 0
DEFAULT_MIN_CHILD_SAMPLES = 20
